Numpy

In [2]:
import numpy as np #importing numpy library

In [8]:
np1 = np.array([1,2,3,4]) #creating array and Array are one dimensional

In [4]:
np1

array([1, 2, 3, 4])

In [5]:
type(np1)

numpy.ndarray

In [9]:
Mat1 = np.array([[1,2], [3,4]]) #creating Matrix and Matrix are two dimensional array

In [10]:
Mat1

array([[1, 2],
       [3, 4]])

In [11]:
np1.shape

(4,)

In [12]:
Mat1.shape

(2, 2)

In [14]:
Mat1.dtype #type of elements in the matrix

dtype('int32')

In [15]:
np1.dtype

dtype('int32')

In [18]:
Mat1[0,0] = 5 #changing elements using index - Here 0th row and 0th column is changed to 5

In [19]:
Mat1

array([[5, 2],
       [3, 4]])

In [20]:
Mat1[0,0] = "String" #All the values must be of same type in the array

ValueError: invalid literal for int() with base 10: 'String'

In [23]:
Mat2 = np.arange(0,10,1) #Creating using range function(Create from 0 to 9 with the step of 1)

In [24]:
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
Mat3 = np.linspace(0,10,20) #it includes the starting point 0 and ending point 10 as well and here 20 is the number of elements we need in this array

In [32]:
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [33]:
Mat3.shape

(20,)

In [35]:
type(Mat3)

numpy.ndarray

In [40]:
Mat4 = np.random.rand(5,5) #Creating a Matrix of 5 rows and 5 columns with assigning random numbers between 0 and 1

In [41]:
Mat4

array([[0.54904765, 0.82244497, 0.64105797, 0.20262704, 0.09325491],
       [0.36650489, 0.83256588, 0.08232342, 0.88115049, 0.47220669],
       [0.36259579, 0.12635962, 0.03236621, 0.31749856, 0.90033658],
       [0.22209348, 0.60110475, 0.51414143, 0.99056477, 0.8021783 ],
       [0.9212896 , 0.76882531, 0.80046533, 0.02964282, 0.19835539]])

In [42]:
Mat4.shape

(5, 5)

In [45]:
Mat5 = np.random.randn(5,5) #creating a 5x5 matrix with random number not only betwwen 0 and 1

In [46]:
Mat5

array([[-0.0319576 , -1.36505097,  1.06757126,  0.49576718, -0.58702452],
       [ 1.09305861, -0.7214583 , -0.99263018, -0.282091  ,  0.46392309],
       [ 1.07422976, -0.04123022, -2.07575701,  0.17451939, -0.37470338],
       [-0.53527347, -0.42212644,  0.19716798, -0.18575859,  0.67064113],
       [-0.14633499,  0.01231046, -0.30068555,  1.15637141, -0.43154693]])

In [47]:
Mat5[0,0]

-0.03195759918862107

In [50]:
Mat5[0,1] #0th index row and 1st index column

-1.3650509736791776

In [55]:
Mat5[0:3,:] #All row from 0th to 2nd index

array([[-0.0319576 , -1.36505097,  1.06757126,  0.49576718, -0.58702452],
       [ 1.09305861, -0.7214583 , -0.99263018, -0.282091  ,  0.46392309],
       [ 1.07422976, -0.04123022, -2.07575701,  0.17451939, -0.37470338]])

In [56]:
Mat5[:,0:3] #All column from 0th to 2nd index

array([[-0.0319576 , -1.36505097,  1.06757126],
       [ 1.09305861, -0.7214583 , -0.99263018],
       [ 1.07422976, -0.04123022, -2.07575701],
       [-0.53527347, -0.42212644,  0.19716798],
       [-0.14633499,  0.01231046, -0.30068555]])