### Classification Models

In [22]:
pwd

'C:\\Users\\HP\\Downloads\\Data Science'

In [23]:
import numpy as np
import pandas as pd
import seaborn as sns

In [24]:
df = pd.read_csv('C:/Users/HP/Downloads/Data Science/Classification data_Python.csv', header = 0)

In [25]:
df.head()

,price,resid_area,air_qual,room_num,age,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks,Sold,avg_dist,airport_YES,waterbody_Lake,waterbody_Lake and River,waterbody_River
0,24.0,32.31,0.538,6.575,65.2,24.7,4.98,5.480,11.19200,23,0.049347,0,4.0875,1,0,0,1
1,21.6,37.07,0.469,6.421,78.9,22.2,9.14,7.332,12.17280,42,0.046146,1,4.9675,0,1,0,0
2,34.7,37.07,0.469,7.185,61.1,22.2,4.03,7.394,46.19856,38,0.045764,0,4.9675,0,0,0,0
3,33.4,32.18,0.458,6.998,45.8,21.3,2.94,9.268,11.26720,45,0.047151,0,6.0650,1,1,0,0
4,36.2,32.18,0.458,7.147,54.2,21.3,5.33,8.824,11.28960,55,0.039474,0,6.0625,0,1,0,0


### Linear Discriminant Analysis

In [26]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [27]:
X_multi = df.loc[:,df.columns != 'Sold']
y_multi = df['Sold']

In [28]:
clf_lda = LinearDiscriminantAnalysis()
clf_lda.fit(X_multi, y_multi)

LinearDiscriminantAnalysis()

In [29]:
y_pred_lda = clf_lda.predict(X_multi)

In [30]:
y_pred_lda

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [31]:
confusion_matrix(y_multi,y_pred_lda)
#rows represent actual class and column represent predicted class
# 192 house not sold in actual data and also not sold in predicted data
#meanwhile 79 houses sold in actual data but not sold in predicted data

array([[192,  84],
       [ 79, 151]], dtype=int64)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X_multi, y_multi, test_size=0.2, random_state=0)

In [33]:
clf_lda_split = LinearDiscriminantAnalysis()
clf_lda_split.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [34]:
y_test_pred_lda_split = clf_lda_split.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [36]:
confusion_matrix(y_test, y_test_pred_lda_split)
#rows represent actual class and column represent predicted class
# 34 house not sold in actual data and also not sold in predicted data
#meanwhile 11 houses sold in actual data but not sold in predicted data

array([[34, 24],
       [11, 33]], dtype=int64)

In [37]:
accuracy_score(y_test, y_test_pred_lda_split)

0.6568627450980392